### ISSUE TITLE
"Nested" Categories during API Export

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#106]
During API exporting, when choosing the option for placing the article under a specific category. A user wanted to know if it would be possible to display the categories with "Nesting" since they may have multiple sub-categories with the same name, and no way to discern between them.

**Comment by PhoenixTilea** [comment]
Honestly, I'm not sure. Because the categories are returned to us in alphabetical order, the only way to do this would be to get every single category at once and sort them. This could be done, but it would be significantly slower. I could look into displaying the parent category's name, but even that might require a bunch of extra api calls to get individual categories. It will depend on if the title of the parent is sent to us in the category data. I'll have to check.

**Comment by thebeardedheathen** [comment]
It looks like calling for a category does provide the parent category.

**Comment by thebeardedheathen** [comment]
I am closing this issue for now. Due to the current setup of WA API, it would require, potentially, hundreds of calls in order to create a nested list of categories during export. This function will be kept as a feature for future consideration, once it is more feasible.
