### ISSUE TITLE
Consider Great Lakes as a Coast

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#68]
Currently, the "coast" in the generator is only a sea or an ocean. However, Great Lakes, have tides and currents and are often larger than seas, meaning they effect weather in similar ways. Settlements that generate on a great lake might say they are hundreds of kilometers from the coast, as this is referring to some nebulous sea or ocean that didn't generate as part of the settlement.

We need a solution for this. Should we distinguish between the coast of a great lake and the coast of the distant sea/ocean, or should we not care about that distant sea/ocean if the settlement generates on a great lake?

**Comment by thebeardedheathen** [comment]
Because "Great Lakes" are roughly equivalent to inland seas. With their own currents and tides, I believe that "Great Lakes" should be identified and separated from the actual "Maritime Coast" This will help with identifying where the settlement is, as well as proving more information for future climate decisions.
